### ISSUE TITLE
SSR Support with template option

### ISSUE THREAD

**Issue by John0x** [vue-typed/vue-typed#10]
As stated in the official documentation:

> The standalone build includes the compiler and supports the template option. It also relies on the presence of browser APIs so you cannot use it for server-side rendering.

The template option is not supported with SSR, which means that we cannot construct components with typescript like the following:
````typescript
@Component({ 
  template: '<span>da</span>'
})
class HomeComponent {
  message: string = 'hello'
}
````

Is there a solution to this problem?

**Comment by budiadiono** [comment]
I'm not sure that I'm understand with this issue, could you provide the example that I can reproduce please? Maybe in [plunker](http://plnkr.co/)?

**Comment by John0x** [comment]
Vue 2 provides server side rendering, the problem with that is, that the template option does not work on the server side, because the api is limited there.
Though there is no solution to it yet, so we can probably close this issue.

My solution is that I just use the vue single-file components, since they are precompiled.
