### ISSUE TITLE
Async Components

### ISSUE THREAD

**Issue by John0x** [vue-typed/vue-typed#11]
Hey, is there already a way to work with async components as described in:
https://vuejs.org/v2/guide/components.html#Async-Components

**Comment by budiadiono** [comment]
Sure, you can use an [@Options](https://vue-typed.github.io/vue-typed/usage/options.html) decorator to create Vue options like this:

```ts
@Options({
  template: '<div>I am async!</div>'
})
class MyComponent {
}
```

and consume it as async component:

```js
Vue.component('async-example', function (resolve, reject) {
  setTimeout(function () {
    // Pass the component definition to the resolve callback
    resolve(MyComponent)
  }, 1000)
})
```

**Comment by John0x** [comment]
Great, thanks :)

**Comment by budiadiono** [comment]
You're welcome :)
