### ISSUE TITLE
Vuex `this.$store` missing from Component

### ISSUE THREAD

**Issue by justrhysism** [vue-typed/vue-typed#12]
I'm not sure how you would want to handle this, but I am using Vuex, and am using `this.$store` as part of a mixin, which Typescript isn't liking :(

**Comment by budiadiono** [comment]
You should have to extends the class to be mixed from `Vue`, for example:

```ts
@Options()
class Bar extends Virtual<Vue>() {

}

@Component()
class Foo extends Mixin(Bar) {
  created() {
    console.log(this.$store);		
  }
}
```

For `Mixins` just simply extends the helper interface from `Vue`:
```ts
@Options()
class Mix1 {

}

@Options()
class Mix2 {

}

interface AllClass extends Mix1, Mix2, Vue {

}

@Component()
class MixAll extends Mixins<AllClass>(Mix1, Mix2) {
  created() {
    console.log(this.$store);		
  }
}
```

**Comment by John0x** [comment]
@budiadiono this sadly doesn't seem to work.

I have tried the following code:
````typescript
<script>
import * as Vue from 'vue'
import { Component, Prop, Virtual, Options, Mixin } from 'vue-typed'

@Options()
class Bar extends Virtual<Vue>() {

}

@Component({})
export default class UserLoginPage extends Mixin(Bar) {
    created() {
        console.log(this.$store.cookies);
    }
}
</script>
````

Always throws:
``error TS2339: Property '$store' does not exist on type 'UserLoginPage'.``

**Comment by budiadiono** [comment]
Maybe you forgot to consume your `store` object in your application? Usually I put my `store` object in my global mixin. In your case as shown in example above you can do:

```ts
<script>
import * as Vue from 'vue'
import { Component, Prop, Virtual, Options, Mixin } from 'vue-typed'

@Options({
  store: yourStoreObject // <-- put your store here or in UserLoginPage component options
})
class Bar extends Virtual<Vue>() {

}

@Component({})
export default class UserLoginPage extends Mixin(Bar) {
    created() {
        console.log(this.$store);
    }
}
</script>
```

**Comment by John0x** [comment]
@budiadiono thank you, this actually works, even though I have had consumed the store object in my app.
Could you maybe give en exampel repo for the method with the global mixin? Thank would be great! :)

**Comment by John0x** [comment]
@budiadiono can you please provide an example how you do it with global mixins?
I've got the $store working, but have problems with other plugins like the vue-cookie plugin, which isn't available no matter what I do.

**Comment by budiadiono** [comment]
@John0x please have a look at [this plunker](http://plnkr.co/5IjQeZ).

**Comment by budiadiono** [comment]
@John0x I'm sorry, think I was giving wrong direction about assign `store` object in a global mixin.  That was bad practice. Assigning `store` object in the main app is enough. I've just updated my plunker [here](http://plnkr.co/edit/7WtzuM?p=preview).
