### ISSUE TITLE
ts error in index.d.ts

### ISSUE THREAD

**Issue by ozeebee** [vue-typed/vue-typed#16]
Hi, I have a TS error in `index.d.ts`:

`Construct signature, which lacks return-type annotation, implicitly has an 'any' return type.`

Indeed, there's a missing return type in line 12 (for the `new ()` construct):
```typescript
export function Mixins<T>(...components: { new (); }[]): VirtualClass<T>
```

**Comment by budiadiono** [comment]
How do you get this error? Can you provide me a repro?

**Comment by ozeebee** [comment]
I've configured my TS project to reject inferred `any` types in order to increase type safety.
 
Here's my `tsconfig.json`:
```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "strict": true,
    "noImplicitReturns": true,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true
  },
  "include": [
    "./src/**/*"
  ]
}
```
So, I left out the `"noImplicitAny": false` setting to achieve this.

Now, I currently work around the problem by explicitly specifying a return value in `index.d.ts`:

```typescript
export function Mixins<T>(...components: { new (): any; }[]): VirtualClass<T> 
```

**Comment by budiadiono** [comment]
Ah I see it now. OK thanks for catching this issue.
