### ISSUE TITLE
How use styles?

### ISSUE THREAD

**Issue by efimov82** [vue-typed/vue-typed#17]
Hello. I am trying to add styles to component like a
 ```
@Component({
	template: `
  <div>
    <input class="my-style" type="text" v-model="message">
    <button @click="clear">Clear</button>
    <div>{{status}}</div>
	</div>
	
	<style>
.my-style {
  width: 100px;
  padding: 10;
}
</style>`
})
export class Container extends Vue {...
```

But it doesn't work. 
How i can add style for component?

**Comment by budiadiono** [comment]
No, you can't put `style` tag inside the `template`. Write style in separated file (eg: css, less, styl, ..), then import it into your `.ts` file.

But If you want to use a [single file component](https://vuejs.org/v2/guide/single-file-components.html) instead, then you can write your `.vue` file like this example:

```
<template lang="pug">
  .main-page
    | {{foo}}
</template>

<script lang="ts">
import Vue from "vue"
import { Component } from "vue-typed"

@Component({})
export default class Index extends Vue {
    foo = "Hi I'm foo!"
}
</script>

<style lang="stylus">
  .main-page
    font-size 16px
</style>

```

**Comment by efimov82** [comment]
Thks) I will try

**Comment by budiadiono** [comment]
You may want to try https://github.com/lempit/quasar-typescript to see how to use style in single file component.
