### ISSUE TITLE
Additional div 

### ISSUE THREAD

**Issue by efimov82** [vue-typed/vue-typed#18]
Hi. I am trying simple example from https://github.com/vue-typed/vue-typed.
Template:

```
<input type="text" v-model="message">
<button v-on:click="clear">Clear</button>
```

When I start ```npm start```
 On source page I see additional DIV 
"`<div class="ginger-module-inputHandlerGhost ginger-module-inputHandlerGhost-textarea"></div>`"
betwen divs 
and button shows on the next line.

but when I build app - all ok. It souse code "ginger-module-inputHandlerGhost" remove and button shows how expected.

What I can to do with this?

**Comment by budiadiono** [comment]
Sorry, I don't quite understand, but I saw that `<input type="text" v-model="message">` has no closing tag. Maybe that was causing the issue?

**Comment by efimov82** [comment]
I try to close it: same results. 
First second when open url see what expected (INPUT + BUTTON at one line), but after some 'magic'  happens and in Body added propperty "ginger_software_stylesheet="true" + additional DIV "class="ginger-module-inputHandlerGhost"

**Comment by efimov82** [comment]
Sorry what bothered. Magic name -  plugin ginger.

**Comment by budiadiono** [comment]
I still don't get it, how does those all `ginger*` stuff coming? can you provide me a repro or something?

**Comment by efimov82** [comment]
Sure. I use Chomium browser and have installed plugin "Spell checker and Grammar checker by Ginger" - he modified DOM model after load page. 
After disabled this plugin - all working well. But don't know why in building app don't have same problem...

**Comment by efimov82** [comment]
Don't know - maybe my questions not relevant this issue: when i reload page F5 - and url looks like "http://localhost:8080/cars" - i see error 'Cannot GET /cars"
but if i start serfing from http://localhost:8080 and GO to http://localhost:8080/cars click on Menu Link - all working well. After F5 - error again... Tried Hot reload module - no effect. Maybe you know how i can fix it?

**Comment by budiadiono** [comment]
Running in development mode is different since we are using webpack HMR, that DOM are frequently updated when changes are made -- a conflict against 3rd party maybe occurred there. 

Maybe disable  the plugin while developing is the best solution. I'm closing this issue since this is not part of VueTyped issue.

**Comment by efimov82** [comment]
Thks for yuor explain
