### ISSUE TITLE
Is there a way to use this with SFC syntax?

### ISSUE THREAD

**Issue by johnnyshankman** [vue-typed/vue-typed#25]
And if so, can we get some documentation and how to correctly set that up? 

I much prefer to use single-file-synax + TS to keep my repos easy to maintain for larger teams. I currently use the class component package for this but would love to switch over to vue-typed ASAP. That's the lynchpin for me!

https://vuejs.org/api/sfc-spec.html

**Comment by budiadiono** [comment]
Hi @johnnyshankman, 

Thanks for interest in this library. Unfortunately, I don't have the time to actively maintain this repository anymore.
I apologize for any inconvenience this may cause.

**Comment by johnnyshankman** [comment]
@budiadiono no problemo! thanks for the transparency! I'll have to stick with https://github.com/vuejs/vue-class-component for now.
