### ISSUE TITLE
Add support for Events, Mixins and Filters

### ISSUE THREAD

**Issue by justrhysism** [vue-typed/vue-typed#4]
Good work on this project so far; however I've had to switch (for now) to [vue-ts-decorate](https://github.com/InDIOS/vue-ts-decorate) as it has support for Events and Mixins.

```
// Events
@On(eventName)
@Once(eventName)

// Mixins
@Mixin()
```

_It would've been good if the author of vue-ts-decorate actually extended an existing project rather than creating his own; maybe that's something which can still happen._

**Comment by budiadiono** [comment]
Hi, this is interesting! Thanks for introduce me [vue-ts-decorate ](https://github.com/InDIOS/vue-ts-decorate). OK I'll take a look and let see what I can do.

**Comment by budiadiono** [comment]
I have moved these issues into: #6, #7, #8 and #9 so it would be easier to track.
