### ISSUE TITLE
Tests are Failing

### ISSUE THREAD

**Issue by justrhysism** [vue-typed/vue-typed#5]
Hi, 

I thought I might have a crack at adding some features to this project, however when I cloned my fork, `npm install`ed and tried to run the tests (`npm test`), I am met with a failure.

https://gist.github.com/justrhysism/78adcafa61cb11b7626c95c7b5c37af6

**Comment by budiadiono** [comment]
I've just tried to make a fresh clone and `npm test` giving different error result on my end. I think this is because of the new version of some node modules installed that is not compatible with the way I'm making unit tests. I confirm this is bug.
